QuizzDynamoApp/urls.py
"""Path for QuizzDynamoApp"""
from django.urls import path
from . import views
app_name = 'QuizzDynamoApp'
urlpatterns = [
    path('',views.WelcomePageMethod,name='Welcome'),
    path('admin/',views.AdminPageMethod,name='Admin'),
    path('QuizzDynamoApp/Home/About',
    views.AboutPageMethod,name='About'),
    path('QuizzDynamoApp/Home/AdminAbout',
    views.AdminAboutPageMethod,name='AdminAbout'),
    path('QuizzDynamoApp/Home/AdminSignOut',
    views.AdminSignOutPageMethod,name='AdminSignOut'),
    path('QuizzDynamoApp/Home/signup/',views.StudentSignUp,name='SignUp'),
    path('QuizzDynamoApp/Home/signin/',views.StudentSignIn,name='SignIn'),
    path('QuizzDynamoApp/Home/signout/',views.StudentSignOut,name='SignOut'),
    path('QuizzDynamoApp/Home/AdminSignIn/',views.AdminSignInMethod,
    name='AdminSignInPage'),
    path('QuizzDynamoApp/Home/AdminSignInModules/',
    views.AdminSignInModulesMethod,name='AdminSignInModulesPage'),
    path('QuizzDynamoApp/Home/AdminStudentSignIn/',
    views.AdminStudentSignInMethod,name='AdminStudentSignInPage'),
    path('QuizzDynamoApp/Home/Bachelors/',views.StudentBachelorsSignUp,
    name='BachelorSignUp'),
    path('QuizzDynamoApp/Home/Masters/',views.StudentMastersSignUp,
    name='MasterSignUp'),
    path('QuizzDynamoApp/Home/PGDiploma/',views.StudentPGDiplomaSignUp,
    name='PGDiplomaSignUp'),
    path('QuizzDynamoApp/Home/AdminModules/',views.AdminUploadMethod,
    name='AdminUploadPage'),
    path('QuizzDynamoApp/Home/AdminStudent/InsertAdminStudent/',
    views.AdminStudentFormMethod,name='AdminStudentInsertPage'),
    path('QuizzDynamoApp/Home/AdminStudent/AdminStudentList/',
    views.AdminStudentListMethod,name='AdminStudentListPage'),
    path('QuizzDynamoApp/Home/AdminStudent/UpdateAdminStudent/<int:id>/',
    views.AdminStudentFormMethod,name='AdminStudentUpdatePage'),
    path('QuizzDynamoApp/Home/AdminStudent/DeleteAdminStudent/<int:id>/',
    views.AdminStudentDelete,name='AdminStudentDeletePage'),
    path('QuizzDynamoApp/Home/BusinessIntelligenceQuiz/',
    views.BusinessIntelligenceQuizMethod,name='BusinessIntelligenceQuizPage'),
    path('QuizzDynamoApp/Home/BusinessIntelligenceQuizSubmission/',
    views.BusinessIntelligenceSubmissionMethod,
    name='BusinessIntelligenceSubmissionPage'),
    path('QuizzDynamoApp/Home/OperatingSystemsQuiz/',
    views.OperatingSystemsQuizMethod,name='OperatingSystemsQuizPage'),
    path('QuizzDynamoApp/Home/OperatingSystemsQuizSubmission/',
    views.OperatingSystemsSubmissionMethod,
    name='OperatingSystemsSubmissionPage'),
    path('QuizzDynamoApp/Home/DatabaseManagementSystemsQuiz/',
    views.DatabaseManagementSystemsQuizMethod,
    name='DatabaseManagementSystemsQuizPage'),
    path('QuizzDynamoApp/Home/DatabaseManagementSystemsQuizSubmission/',
    views.DatabaseManagementSystemsSubmissionMethod,
    name='DatabaseManagementSystemsSubmissionPage'),
    path('QuizzDynamoApp/Home/LinuxQuiz/',views.LinuxQuizMethod,
    name='LinuxQuizPage'),
    path('QuizzDynamoApp/Home/LinuxQuizSubmission/',
    views.LinuxSubmissionMethod,name='LinuxSubmissionPage'),
    path('QuizzDynamoApp/Home/JavaQuiz/',views.JavaQuizMethod,
    name='JavaQuizPage'),
    path('QuizzDynamoApp/Home/JavaQuizSubmission/',views.JavaSubmissionMethod,
    name='JavaSubmissionPage'),
    path('QuizzDynamoApp/Home/NetworkingConceptsQuiz/',
    views.NetworkingConceptsQuizMethod,name='NetworkingConceptsQuizPage'),
    path('QuizzDynamoApp/Home/NetworkingConceptsQuizSubmission/',
    views.NetworkingConceptsSubmissionMethod,
    name='NetworkingConceptsSubmissionPage'),
    path('QuizzDynamoApp/Home/SocialNetworkAnalysisQuiz/',
    views.SocialNetworkAnalysisQuizMethod,
    name='SocialNetworkAnalysisQuizPage'),
    path('QuizzDynamoApp/Home/SocialNetworkAnalysisQuizSubmission/',
    views.SocialNetworkAnalysisSubmissionMethod,
    name='SocialNetworkAnalysisSubmissionPage'),
    path('QuizzDynamoApp/Home/AlgorithmsQuiz/',views.AlgorithmsQuizMethod,
    name='AlgorithmsQuizPage'),
    path('QuizzDynamoApp/Home/AlgorithmsQuizSubmission/',
    views.AlgorithmsSubmissionMethod,name='AlgorithmsSubmissionPage'),
    path('QuizzDynamoApp/Home/WebDesign&AppQuiz/',views.WebDesignAppQuizMethod,
    name='WebDesignAppQuizPage'),
    path('QuizzDynamoApp/Home/WebDesign&AppQuizSubmission/',
    views.WebDesignAppSubmissionMethod,name='WebDesignAppSubmissionPage'),
    path('QuizzDynamoApp/Home/InternetworkingQuiz/',
    views.InternetworkingQuizMethod,name='InternetworkingQuizPage'),
    path('QuizzDynamoApp/Home/InternetworkingQuizSubmission/',
    views.InternetworkingSubmissionMethod,name='InternetworkingSubmissionPage'),
    path('QuizzDynamoApp/Home/MobileDevelopmentQuiz/',
    views.MobileDevelopmentQuizMethod,name='MobileDevelopmentQuizPage'),
    path('QuizzDynamoApp/Home/MobileDevelopmentQuizSubmission/',
    views.MobileDevelopmentSubmissionMethod,
    name='MobileDevelopmentSubmissionPage'),
]

QuizzDynamoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('QuizzDynamoApp.urls'))
]

QuizzDynamoApp/forms.py
"""Form for Student, Quiz and Admin """
from django import forms
from django.core import validators
from .models import Student, Admin
class StudentSignInForm(forms.Form):
    """Form for SignIn Page """
    username = forms.CharField(label="Username")
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
class StudentSignUpForm(forms.ModelForm):
    """Form for Student Sign Up with validations"""
    name_regex = r"\A[a-zA-Z]+\Z"
    username_regex = r"^[a-zA-Z0-9]+$"
    min_length = 2
    max_length = 25
    validation_msg_min = f"Should have at least {min_length} characters"
    validation_msg_max = f"Should have at most {max_length} characters"
    first_name = forms.CharField(validators=[
        validators.MinLengthValidator(min_length, validation_msg_min),
        validators.MaxLengthValidator(max_length, validation_msg_max),
        validators.RegexValidator(name_regex)
    ])
    last_name = forms.CharField(validators=[
        validators.MinLengthValidator(min_length, validation_msg_max),
        validators.MaxLengthValidator(max_length, validation_msg_max),
        validators.RegexValidator(name_regex)
    ])
    username = forms.CharField(validators=[
        validators.MinLengthValidator(min_length, validation_msg_min),
        validators.MaxLengthValidator(max_length, validation_msg_max),
        validators.RegexValidator(username_regex)])
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)
    DEGREE_CHOICES = (
    ('Bsc','Bsc'),
    ('Msc','Msc'),
    ('PGDiploma','PGDiploma'),
    )
    degree = forms.ChoiceField(choices=DEGREE_CHOICES, widget=forms.Select)
    class Meta:
        """Subclass for Student"""
        model = Student
        fields = ['first_name', 'last_name', 'username', 'password1',
        'password2', 'degree']
        widgets = {
            'password1': forms.PasswordInput(),
            'password2': forms.PasswordInput(),
        }
class AdminSignInForm(forms.ModelForm):
    """Form for Admin Page"""
    username = forms.CharField(label="Username")
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    class Meta:
        """Subclass for Admin"""
        model = Admin
        fields = ['username', 'password']

QuizzDynamoApp/views.py
"""View for QuizzDynamo"""
import csv
import io
from django.views.decorators.http import require_http_methods
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect
from django.template import loader
from django.http import HttpResponse
from django.contrib import messages
from django.http import JsonResponse
from .models import Student, Quiz, Admin
from .forms import StudentSignUpForm, StudentSignInForm, AdminSignInForm

@require_http_methods(["GET", "POST"])
def WelcomePageMethod(request):
    """Welcome Page for QuizzDynamo. Loads StudentSignUpForm and it's fields in 
    the page"""
    context = {'form': StudentSignUpForm()}
    return render(request, 'QuizzDynamoApp/Welcome.html', context)

def AboutPageMethod(request):
    """About Page for QuizzDynamo"""
    template_about = loader.get_template('QuizzDynamoApp/About.html')
    context = {'template_about':template_about}
    return HttpResponse(template_about.render(context, request))

def AdminAboutPageMethod(request):
    """Admin About Page for QuizzDynamo"""
    template_adminabout = loader.get_template('QuizzDynamoApp/AdminAbout.html')
    context = {'template_adminabout':template_adminabout}
    return HttpResponse(template_adminabout.render(context, request))

def AdminSignOutPageMethod(request):
    """Admin Sign Out Page for QuizzDynamo"""
    template_adminsignout = loader.get_template('QuizzDynamoApp/AdminSignOut.html')
    context = {'template_adminsignout':template_adminsignout}
    return HttpResponse(template_adminsignout.render(context, request))

def AdminPageMethod(request):
    """Bringing up the Admin Page for necessary changes"""
    admin_page = Admin.objects.all(username=username)# pylint: disable=E0602
    return render(request, 'QuizzDynamoApp/Admin.html', {'form': admin_page})

def AdminSignInMethod(request):
    """Sign Up Page for Admin"""
    if request.method == 'POST':
        form = AdminSignInForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            try:
                admincheck = Admin.objects.get(username=username)
            except ObjectDoesNotExist:
                error_message = "User does not exist. Please check your username."
                return render(request, "QuizzDynamoApp/AdminSignIn.html",
                {'form': form, 'error_message': error_message})
            if  admincheck:
                if admincheck.password == password:
                    return redirect('QuizzDynamoApp:Admin')
            else:
                error_message = 'Invalid username or password.'
                return render(request, 'QuizzDynamoApp/AdminSignIn.html',
                {'form': form, 'error_message': error_message})
    else:
        form = AdminSignInForm()
    return render(request, 'QuizzDynamoApp/AdminSignIn.html', {'form': form})

def AdminSignInModulesMethod(request):
    """Sign Up Page for Admin Modules"""
    if request.method == 'POST':
        form = AdminSignInForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            try:
                admincheck = Admin.objects.get(username=username)
            except ObjectDoesNotExist:
                error_message = "User does not exist. Please check your username."""
                return render(request, "QuizzDynamoApp/AdminSignInModules.html",
                {'form': form, 'error_message': error_message})
            if  admincheck:
                if admincheck.password == password:
                    return redirect('QuizzDynamoApp:AdminUploadPage')
            else:
                error_message = 'Invalid username or password.'
                return render(request, 'QuizzDynamoApp/AdminSignInModules.html',
                {'form': form, 'error_message': error_message})
    else:
        form = AdminSignInForm()
        return render(request, 'QuizzDynamoApp/AdminSignInModules.html',
        {'form': form})

def AdminStudentSignInMethod(request):
    """Sign Up Page for Admin Modules"""
    if request.method == 'POST':
        form = AdminSignInForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            try:
                admincheck = Admin.objects.get(username=username)
            except ObjectDoesNotExist:
                error_message = "User does not exist. Please check your username."""
                return render(request, "QuizzDynamoApp/AdminStudentSignIn.html",
                {'form': form, 'error_message': error_message})
            if  admincheck:
                if admincheck.password == password:
                    return redirect('QuizzDynamoApp:AdminStudentInsertPage')
            else:
                error_message = 'Invalid username or password.'
                return render(request, 'QuizzDynamoApp/AdminStudentSignIn.html',
                {'form': form, 'error_message': error_message})
    else:
        form = AdminSignInForm()
    return render(request, 'QuizzDynamoApp/AdminStudentSignIn.html',
    {'form': form})

def StudentSignUp(request):
    """Sign Up Page. Responsible for bringing up three different pages for BSc,
    MSc and PGDiploma on user submission of the degree"""
    if request.method == "POST":
        try:
            studentsignupform = StudentSignUpForm(request.POST)
            if studentsignupform.is_valid():
                student = studentsignupform.save()
                studentsignupformusername = student.username
                messages.success(request,
                f"Account created for {studentsignupformusername}")
                degree = student.degree
                if(degree == 'Bsc'):
                    return redirect('QuizzDynamoApp:BachelorSignUp')
                elif(degree == 'Msc'):
                    return redirect('QuizzDynamoApp:MasterSignUp')
                elif(degree == 'PGDiploma'):
                    return redirect('QuizzDynamoApp:PGDiplomaSignUp')
            else:
                messages.error(request, "There was an error signing up")
                return redirect('QuizzDynamoApp:Welcome')
        except Exception as e:# pylint: disable=W0718
            messages.error(request,
            "There was an error creating your account", e)
            return redirect('QuizzDynamoApp:Welcome')
    elif request.method == "GET":
        studentsignupform = StudentSignUpForm()
        return render(request, "QuizzDynamoApp/Welcome.html",
        {'form': studentsignupform})

def StudentSignIn(request):
    """Sign In Page. Responsible for bringing up three different pages for BSc, 
    MSc and PGDiploma on user submission of the degree"""
    if request.method == "POST":
        studentsigninform = StudentSignInForm(request.POST)
        username = request.POST.get('username')
        password = request.POST.get('password')
        try:
            studentcheck = Student.objects.get(username=username)
        except ObjectDoesNotExist:
            error_message = "User does not exist. Please check your username."
            return render(request, "QuizzDynamoApp/SignIn.html",
            {'form': studentsigninform, 'error_message': error_message})
        if studentcheck.password1 == password:
            if studentcheck.degree == 'Bsc':
                return redirect('QuizzDynamoApp:BachelorSignUp')
            elif studentcheck.degree == 'Msc':
                return redirect('QuizzDynamoApp:MasterSignUp')
            elif studentcheck.degree == 'PGDiploma':
                return redirect('QuizzDynamoApp:PGDiplomaSignUp')
        error_message = "Invalid username or password."
        return render(request, "QuizzDynamoApp/SignIn.html",
        {'form': studentsigninform, 'error_message': error_message})
    studentsigninform = StudentSignInForm()
    return render(request, "QuizzDynamoApp/SignIn.html",
    {'form': studentsigninform})

def StudentSignOut(request):
    """User Sign Out for QuizzDynamo"""
    template_usersignout = loader.get_template('QuizzDynamoApp/SignOut.html')
    context = {'template_usersignout':template_usersignout}
    return HttpResponse(template_usersignout.render(context, request))

def StudentBachelorsSignUp(request):
    """Bachelor's Degree Quiz Page and it's respective subjects"""
    bsc_degree = Student.objects.get(degree='Bsc')
    return render(request, 'QuizzDynamoApp/Bachelors.html', {'form':bsc_degree})

def StudentMastersSignUp(request):
    """Master's Degree Quiz Page and it's respective subjects"""
    msc_degree = Student.objects.get(degree='Msc')
    return render(request, 'QuizzDynamoApp/Masters.html', {'form':msc_degree})

def StudentPGDiplomaSignUp(request):
    """PG Diploma Degree Quiz Page and it's respective subjects"""
    pgdiploma_degree = Student.objects.get(degree='PGDiploma')
    return render(request, 'QuizzDynamoApp/PGDiploma.html',
    {'form':pgdiploma_degree})

def AdminUploadMethod(request):
    """Admin Page for uploading the csv files for the quizzes"""    
    template = "QuizzDynamoApp/AdminModules.html"
    data = Quiz.objects.all()
    prompt = {
        'order': 'Order of the CSV should be question_text, option_a, option_b, option_c, option_d',
        'quizzes': data    
    }
    if request.method == "GET":
        return render(request, template, prompt)
    csv_file = request.FILES.get('file')
    if not csv_file:
        messages.error(request, 'No file uploaded! Refresh to upload a file!')
        return render(request, template, prompt)
    if not csv_file.name.endswith('.csv'):
        messages.error(request, 'THIS IS NOT A CSV FILE')
        return render(request, template, prompt)
    data_set = csv_file.read().decode('UTF-8')
    io_string = io.StringIO(data_set)
    next(io_string)

QuizzDynamoApp/templates/QuizzDynamoApp/AdminStudent.html
<!--Admin Student Page-->
{% load static %} 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" 
href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" 
crossorigin="anonymous">
    <title>QuizzDynamo</title>
           <link rel="stylesheet" 
           href="{% static 'QuizzDynamoApp/css/adminstudentstyles.css' %}">  
    <link rel = "stylesheet" 
href = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
</head>
<style>
</style>
<body>
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <div class="collapse navbar-collapse justify-content-flex-start">
            <ul class="navbar-nav">
                 <li class="nav-item">
                    <a class="nav-link" 
                href="{%url 'QuizzDynamoApp:AdminSignOut'%}">Admin Sign Out</a>
                </li>
            </ul>
        </div>
        <nav class="navbar-brand">QuizzDynamo</nav>
         <div class="collapse navbar-collapse justify-content-end">
             <ul class="navbar-nav">
               <li class="nav-item">
                    <a class="nav-link" 
                    href="{%url 'QuizzDynamoApp:AdminAbout'%}">Admin About</a>
                </li>
        </div>
    </div>
  </nav>
{% block content %}
<div class="container">
    <div class="col-md-10 offset-md-1 mt-5">
        <div class="jumbotron">
            <h1 class="display-4">Student Register</h1>
            <p class="lead">Student List for QuizzDynamoApp</p>
            <hr class="my-4">
            <form action="" method="post" autocomplete="off">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="form-group">
                    <label for="id_student_first_name">First Name:</label>
                    {{ form.first_name }}
                </div>
                <div class="form-group">
                    <label for="id_student_last_name">Last Name:</label>
                    {{ form.last_name }}
                </div>
                <div class="form-group">
                    <label for="id_student_username">Username:</label>
                    {{ form.username }}
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="id_student_degree">Degree:</label>
                            {{ form.degree }}
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="id_student_password1">Password:</label>
                            {{ form.password1 }}
                        </div>
                        <div class="form-group">
                <label for="id_student_password2">Enter Password Again:</label>
                            {{ form.password2 }}
                        </div>
                    </div>
                </div>
<button type="submit" class="btn btn-success btn-block btn-lg" 
href = "{% url 'QuizzDynamoApp:AdminStudentListPage' %}">
                    <i class="fas fa-database"></i> Submit
                </button>
                <a href="{% url 'QuizzDynamoApp:AdminStudentListPage' %}" 
                class="btn btn-secondary btn-block btn-lg">
                    <i class="fas fa-stream"></i> Student List
                </a>
            </form>
        </div>
    </div>
</div>
{% endblock content %}
<footer class="bg-dark text-white text-center text-lg-start fixed-bottom">
  <div class="container-fluid p-3 row justify-content-center">
    <div class="row">
     <div class="text-center">
       © Copyright: QuizzDynamo
     </div>
    </div>
  </div>
</footer>
</body>
</html>

QuizzDynamoApp/templates/QuizzDynamoApp/AdminStudentList.html
<!--Admin Student List-->
{% load static %} 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" 
href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" 
crossorigin="anonymous">
    <title>QuizzDynamo</title>
    <link rel = "stylesheet" 
href = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
</head>

<body>
   <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <div class="collapse navbar-collapse justify-content-flex-start">
            <ul class="navbar-nav">
                 <li class="nav-item">
                    <a class="nav-link" 
                href="{%url 'QuizzDynamoApp:AdminSignOut'%}">Admin Sign Out</a>
                </li>
            </ul>
        </div>
        <nav class="navbar-brand">QuizzDynamo</nav>
         <div class="collapse navbar-collapse justify-content-end">
             <ul class="navbar-nav">
               <li class="nav-item">
                    <a class="nav-link" 
                href="{%url 'QuizzDynamoApp:AdminAbout'%}">Admin About</a>
                </li>
        </div>
    </div>
  </nav>
{% block content %}  
<table class="table table-borderless">
    <thead class="border-bottom font-weight-bold">
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Username</th>
            <th>Degree</th>
            <th>
<a href="{% url 'QuizzDynamoApp:AdminStudentInsertPage' %}" 
class="btn btn-outline-success">
                    <i class="fas fa-plus"></i> Add New Student
                </a>
            </th>
        </tr>
    </thead>
    <tbody>
        {% for AdminStudent in AdminStudentList %}
        <tr>
            <td>{{ AdminStudent.first_name }}</td>
            <td>{{ AdminStudent.last_name }}</td>
            <td>{{ AdminStudent.username }}</td>
            <td>{{ AdminStudent.degree }}</td>
            <td>
<a href="{% url 'QuizzDynamoApp:AdminStudentUpdatePage' AdminStudent.id %}" 
class="btn text-secondary px-0">
                    <i class="far fa-edit fa-lg"></i>
                </a>
<form action="{% url 'QuizzDynamoApp:AdminStudentDeletePage' AdminStudent.id %}" 
method="post" class="d-inline">
                    {% csrf_token %}
                    <button type="submit" class="btn">
                        <i class="far fa-trash-alt fa-lg text-danger"></i>
                    </button>
                </form>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}
<footer class="bg-dark text-white text-center text-lg-start fixed-bottom">
  <div class="container-fluid p-3 row justify-content-center">
    <div class="row">
     <div class="text-center">
       © Copyright: QuizzDynamo
     </div>
    </div>
  </div>
</footer>
</body>
</html>

QuizzDynamoApp/templates/QuizzDynamoApp/PGDiploma.html
{% load static %} 
<!DOCTYPE html>
<!--PG Diploma Quiz Page-->
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link 
href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
rel="stylesheet">
    <title>QuizzDynamo</title>
    <link rel="stylesheet" 
    href="{% static 'QuizzDynamoApp/css/newpgdiplomastyles.css' %}">  
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <div class="collapse navbar-collapse justify-content-flex-start">
            <ul class="navbar-nav">
            </ul>
        </div>
        <nav class="navbar-brand">QuizzDynamo</nav>
         <div class="collapse navbar-collapse justify-content-end">
             <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" 
                    href="{%url 'QuizzDynamoApp:SignOut'%}">Sign Out</a>
                </li>
        </div>
    </div>
  </nav>
  {% block content %}
<div class="form-headingdetail">
    <h2>Subjects</h2>
</div>
<!--Username and degree-->
<div class="tableusers">
    <table border="2">
        <thead></thead>
        <tbody>
        <tr>
            <td><b>Username</b></td>
            <td><b>{{ form.username }}</b></td>
        </tr>
        <tr>
            <td><b>Degree</b></td>
            <td><b>{{ form.degree }}</b></td>
        </tr>
        </tbody>
    </table>
</div>
 {% endblock content %}
<div class="custom-KeyPriorityDepartmentHeading">
    <div class="columnDepartment">
        <h2>PG Diploma</h2>
        <a href = "{% url 'QuizzDynamoApp:WebDesignAppQuizPage' %}" 
        class="buttonColumn">Web Design & Applications</button>
        <a href = "{% url 'QuizzDynamoApp:InternetworkingQuizPage' %}" 
        class="buttonColumn">Internetworking</button>
        <a href = "{% url 'QuizzDynamoApp:MobileDevelopmentQuizPage' %}" 
        class="buttonColumn">Mobile Development</button>
    </div>
</div>
<footer class="bg-dark text-white text-center text-lg-start fixed-bottom">
  <div class="container-fluid p-3 row justify-content-center">
    <div class="row">
     <div class="text-center">
       © Copyright: QuizzDynamo
     </div>
    </div>
  </div>
</footer>
</body>
</html>